---
title: "Homework 2: Group 1"
date: "`r format(Sys.time(), '%d %B, %Y')`"
author: "Gaëtan Lovey, Raffaello Raffin, Jérémy Bayer, Cédric Vuignier" 
output:
  rmdformats::readthedown:
    self_contained: true
    code_folding: hide
    toc_depth: 4

---


```{r message=FALSE, warning=FALSE, include=FALSE}
library(here)
library(kableExtra)
library(tidyverse)
library(ggplot2)
```

#Goals of the project
```{r}


```

#schedule

```{r }
week <- c("7", "8", "9", "10", "11", "12","13","14")

date <- c("Oct. 26", "Nov. 2","Nov. 9",  "Nov. 16","Nov. 30","Dec. 7","Dec. 14")

task <- c("project proposal", "data scrapping", "data scrapping + EDA part", "Shiny App",
          "Shiny App", "12","13","14")

person <- c("7", "8", "9", "10", "all group", "all group","all group","all group")

timetable <- cbind(week, date, task, person)

colnames(timetable) <- c("week", "date", "Task", "Person")

timetable %>% kable() %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    font_size = 12,
    full_width = T
  ) 


```

